### ISSUE TITLE
install.py fails with python3

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/regent-fft#1]
install.py currently fails its execution with python3 with the following error:
```
Traceback (most recent call last):
  File "./install.py", line 73, in <module>
    driver(**vars(args))
  File "./install.py", line 50, in driver
    download(fftw_tar, 'http://www.fftw.org/%s.tar.gz' % fftw_basename, '59831bd4b2705381ee395e54aa6e0069b10c3626')
  File "./install.py", line 27, in download
    shasum.communicate('%s  %s' % (sha1, dest_file))
  File "/home/mario/miniconda3/lib/python3.8/subprocess.py", line 1009, in communicate
    self._stdin_write(input)
  File "/home/mario/miniconda3/lib/python3.8/subprocess.py", line 958, in _stdin_write
    self.stdin.write(input)
TypeError: a bytes-like object is required, not 'str'
```

The error is fixed with this patch:
```
diff --git a/install.py b/install.py
index ef62f98..659e993 100755
--- a/install.py
+++ b/install.py
@@ -24,7 +24,7 @@ def download(dest_path, url, sha1):
     subprocess.check_call(['wget', '-O', dest_path, url])
     shasum = subprocess.Popen(
         ['shasum', '--check'], stdin=subprocess.PIPE, cwd=dest_dir)
-    shasum.communicate('%s  %s' % (sha1, dest_file))
+    shasum.communicate(('%s  %s' % (sha1, dest_file)).encode())
     assert shasum.wait() == 0

 def driver(thread_count):
```

**Comment by elliottslaughter** [comment]
Done, and I bumped the `#!` line to `python3` so that hopefully I can avoid introducing more Python 3 issues in the future. (The script is still Python 2 compatible for the moment but I will probably not watch this too closely, since Python 2 is EOL already.)

**Comment by mariodirenzo** [comment]
Ok, thanks!
